//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angielski.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angielski.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acquired : nabyty
        ///acquired immune deficiency syndrome : Zespół nabytego niedoboru odpornościowego
        ///addiction : uzależnienie
        ///ailment : choroba, cierpienie
        ///angina pectoris : dusznica bolesna
        ///chicken-pox : ospa wierzna	
        ///communicable disease : choroba zakaźna
        ///coronary thrombosis : zakrzepica tętnicywieńcowej
        ///cure : leczenie
        ///diabetes : cukrzyca
        ///diphteria : błonnica
        ///failure : niewydolność
        ///fatal : śmiertelny
        ///german measles : różyczka
        ///gout : dna, skaza moczanowa
        ///legionnaires disease : choroba legionis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit1 {
            get {
                return ResourceManager.GetString("book_2_unit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brittle:łamliwy, kruchy
        ///concomitant:współistniejący
        ///compensate:rekompensować
        ///cortical:korowy
        ///densitometry: pomiar gęstości
        ///density:gęstość
        ///emphysema:rozedma płuc
        ///falure:niewydolność
        ///fracture:złamanie
        ///fragile:łamliwy
        ///hump:garbić się
        ///malabsorption:złe wchłanianie 
        ///porous:porowaty
        ///osteoporosis: zeszrotnienie kości/osteoporoza
        ///resorption:wchłanianie
        ///response:odpowiedź
        ///respond:odpowiadać
        ///stabbing:przeszywający
        ///progressive: postępująca
        ///bony tissue:tkanka kostna
        ///common among the eldery:?
        ///relat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit11 {
            get {
                return ResourceManager.GetString("book_2_unit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjunctive:pomocniczy
        ///complexion:cera
        ///graft:przeszczep
        ///itch:swędzieć
        ///junction:połączenie
        ///melanoblast:kom wytwarzająca melaninę
        ///melanoma: czerniak
        ///mole:znamię
        ///recurrence:nawrót
        ///survival:przeżycie
        ///refers: odwołać się
        ///malignant lesion: zołośliwe zmiany
        ///affected:zaatakowany
        ///rarely: rzadko
        ///slighty raised: lekko wypukła
        ///flat: płaski
        ///existing: istniejący
        ///exposure: wystawienie na
        ///metastases: przerzuty 
        ///consist:składać się
        ///involves: wymagać
        ///depends: zależeć
        ///thickness: gęstość 
        ///promotes: promow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit12 {
            get {
                return ResourceManager.GetString("book_2_unit12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to azospermia: brak plemników
        ///conceive: począć
        ///conception:poczęcie
        ///defective: uszkodzony
        ///displacement:przemieszczenie
        ///ectopic pregnancy: ciąża pozamaciczna
        ///endometriosis: gruczolistość
        ///fallopian tube: jajowód
        ///Favourable: sprzyjający
        ///fertilize:zapłodnić
        ///fibroid: włóknistu
        ///gonorrhoea: rzeżączka
        ///hostile: wrogi
        ///hypogonadism: niedoczynność gonad
        ///immobilize: unieruchomić
        ///infertility: bezpłodność
        ///insemination: zaplemnienie
        ///malformation: wada rozwojowa
        ///myoma:mięśniak
        ///oligospermia: za mało plemników        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit16 {
            get {
                return ResourceManager.GetString("book_2_unit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contagious : zakaźny
        ///contaminate : skazić, zanieczyścić
        ///discharge : wydzielina
        ///droplet : kropelka
        ///iatrogenic : jatrogenny, spowodowany przez lekarza
        ///lozenge : pastylka do ssania
        ///malaise : złe samopoczucie
        ///myxovirus : miksowirus
        ///nutritional : dotyczący odżywiania
        ///resistance : odporność, oporność
        ///subside : cofać się (o chorobie objawach), ustępować
        ///infectious : Zakaźny
        ///communicable : zaraźliwy
        ///transmissible : zaraźliwe
        ///idiopathic : bez samoistnej przyczyny
        ///reportable : choroba podlegająca zgłos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit2 {
            get {
                return ResourceManager.GetString("book_2_unit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antacid : związek zobojętniający kwas
        ///barium meal : papka barowa podawana do połknięcia przed badaniem RTG
        ///belching : odbijanie się
        ///combat : zwalczyć
        ///distension : rozdęcie, wzdęcie
        ///eradicate : wytępić wyniszczyć (bakterie, zakażenie)
        ///eradication : wytępienie wyniszczenie, likwidacja zakażenia
        ///erosion : nadżerka
        ///exacerbation : zaostrzenie (objawów)
        ///gnawing : gryzący
        ///H2-Receptor blocker (&quot;2&quot; na dole) : bloker receptorów wodorowych
        ///heal : goić się
        ///heartburn : zgaga
        ///intermittent : przerywany
        ///proto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit4 {
            get {
                return ResourceManager.GetString("book_2_unit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adenocarcinoma : gruczolakorak, rak gruczołowy
        ///colitis : zapalenie okrężnicy
        ///colonoscopy : wziernikowanie okrężnicy
        ///colostomy : wytworzenie przetoki okrężniczo-skórnej, kolostomia
        ///excise : wyciąć
        ///extent : zakres, zasięg
        ///faeces : kał
        ///flexible : giętki
        ///forceps : kleszcze, szczypce
        ///incision : nacięcie
        ///laparotomy : otwarcie jamy brzusznej
        ///maligmant : złośliwy
        ///polyposis : polipowatość
        ///rectoscopy : wziernikowanie odbytnicy
        ///relapse : nawrót choroby
        ///sample : próbka
        ///specimen : Próbka
        ///ulcerative : wr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit5 {
            get {
                return ResourceManager.GetString("book_2_unit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adolescence : okres dojrzewania
        ///ensure : zapewnić
        ///fasting : na czczo
        ///gangrene : gangrena
        ///hyperglycaemia : podwższony poziom glukozy we krwii
        ///hypoglycaemia : hipoglikemia
        ///nephropathy : nefropatia
        ///neuropathy : neuropatia
        ///retinopathy : retinopatia
        ///source : źródło
        ///suscepitibility : podatność (na chorobę), skłonność
        ///diabetes mellitus : cukrzyca
        ///pancreas : trzustka
        ///islets of Langerhans : wysepki Langerhansa
        ///cappilaries : naczynka
        ///subcutaneus : podskórny
        ///atherosclerosis : miażdżyca
        ///cardiovascular  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book_2_unit6 {
            get {
                return ResourceManager.GetString("book_2_unit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angiography : angiografia
        ///atheroma : ognisko miażdżycowe
        ///bypass : przepływ omijający, połączenie omijające - utworzenie przepływu omijającego
        ///concious : przytomny
        ///conciousness : świadomość
        ///contract : kurczyć
        ///crushing  : miażdżący
        ///emboli : czopy zatorowe
        ///embolus : czop zatorowy
        ///embolism : zator
        ///fibrillation : drżenie włókienkowe, migotanie
        ///graft : przeszczep
        ///hyperlipidemia : podwyższony poziom lipidów
        ///insufficiency : niewydolność, niedobór
        ///ischaemia : niedokrwienie
        ///necrosis : martwica
        ///pacemak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string book2_unit3 {
            get {
                return ResourceManager.GetString("book2_unit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acquired : nabyty
        ///acquired immune deficiency syndrome : Zespół nabytego niedoboru odpornościowego
        ///addiction : uzależnienie
        ///ailment : choroba, cierpienie
        ///angina pectoris : dusznica bolesna
        ///chicken-pox : ospa wierzna	
        ///communicable disease : choroba zakaźna
        ///coronary thrombosis : zakrzepica tętnicywieńcowej
        ///cure : leczenie
        ///diabetes : cukrzyca
        ///diphteria : błonnica
        ///failure : niewydolność
        ///fatal : śmiertelny
        ///german measles : różyczka
        ///gout : dna, skaza moczanowa
        ///legionnaires disease : choroba legionis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_All {
            get {
                return ResourceManager.GetString("English_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zła wartość.
        /// </summary>
        internal static string Form1_textBox1_TextChanged_Zła_wartość {
            get {
                return ResourceManager.GetString("Form1_textBox1_TextChanged_Zła_wartość", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za dużo liter.
        /// </summary>
        internal static string Form2_buttonCheck_Click_Za_dużo_liter {
            get {
                return ResourceManager.GetString("Form2_buttonCheck_Click_Za_dużo_liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alveolus - pęcherzyk płucny
        ///respiratory system - układ oddechowy
        ///sac  - pęcherzyk
        ///tonsil - migdałek
        ///visceral - trzewny
        ///attach - przyłączyć
        ///basc - podstawa
        ///bloodstream - krwioobieg
        ///pharynx - gardło
        ///larynx - Krtań
        ///trachea - tchawica
        ///bronchi (pl), bronchus (sing)  - oskrzela
        ///bronchiole - oskrzelik
        ///cone - stożek
        ///factor - czynnik
        ///hoarseness - chrypka
        ///hurt - zranienie
        ///laryngopharynx - krtaniowa część gardła
        ///line - linia, wyścielić
        ///lobe - płat
        ///lung - płuco
        ///alveoli of the lungs - pęcherzyki plu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slowaAng {
            get {
                return ResourceManager.GetString("slowaAng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acquired : nabyty
        ///acquired immune deficiency syndrome : Zespół nabytego niedoboru odpornościowego
        ///addiction : uzależnienie
        ///ailment : choroba, cierpienie
        ///angina pectoris : dusznica bolesna
        ///chicken-pox : ospa wierzna	
        ///diabetes : cukrzyca
        ///communicable disease : choroba zakaźna
        ///coronary thrombosis : zakrzepica tętnicywieńcowej
        ///cure : leczenie
        ///diabetes : cukrzyca.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aim : cel celować
        ///approach : podejście
        ///area : obszar
        ///complain : skarżyć się, narzekać
        ///complaint : skarga, dolegliwość
        ///concern : zainteresować, dotyczyć, zajmować się
        ///consideration : rozwaga 
        ///take into consideration : wziąć, brać coś pod uwagę
        ///cure : leczyć, wyleczyć
        ///dietician : dietetyk
        ///duty : obowiązek, dyżur
        ///enviroment : otoczenie, środowisko
        ///examination : badanie
        ///physical examination : badanie fizykalne
        ///general practitioner : lekarz ogólny
        ///A gynaecologist : ginekolog
        ///indicate : wskazać, z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit_17 {
            get {
                return ResourceManager.GetString("unit_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bone marrow : szpik kostny
        ///counselling : poradnictwo
        ///donor : dawca
        ///excision : wycięcie
        ///immune system : układ odpornościowy
        ///immunosuppressant : środek immunosupresyjny
        ///laser : laser
        ///lithotripsy : kruszenie kamieni
        ///palliative : paliatywny, łagodzący
        ///recipient : biorca
        ///rejection : odrzucenie
        ///substitute : substytut, zastępowainie, podstawianie
        ///tiny : mały
        ///ultrasonography : ultrasonografia
        ///radiation therapy : radioterapia
        ///endoscope : endoskop
        ///transplant surgery : operacja przeszczepu
        ///hip joint : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit_19 {
            get {
                return ResourceManager.GetString("unit_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdomen : jama brzuszna
        ///affect : atakować
        ///ankle : kostka u nogi
        ///arm : ramię
        ///armpit : pacha
        ///bend : schylać się, zginać
        ///body : ciało
        ///bone : kość
        ///calf : łydka
        ///cavity : jama
        ///cell : komórka
        ///cheek : policzek
        ///chest : klatka piersiowa
        ///chin : broda, podbródek
        ///consist : składać się
        ///diaphragm : przepona
        ///elbow : łokieć
        ///eye : oko
        ///eyelash: rzęsa
        ///eyelid : powieka
        ///face : twarz
        ///foot, (pl. feet) : stopa, stopy
        ///forearm : przedramię
        ///forehead : czoło
        ///groin : pachwina
        ///hand : ręka, dłoń
        ///head : głowa
        ///hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit1 {
            get {
                return ResourceManager.GetString("unit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular system : układ sercowo:naczyniowy
        ///blood vessels : naczynia krwionośne
        ///arteries : tętnice
        ///arterioles : tętniczki
        ///capillaries : naczynka
        ///venules : żyłki
        ///cone-shaped : stożkowy
        ///hollow : pusty
        ///apex : wierzchołek
        ///pericardium : osierdzie
        ///myocardium : mięsień sercowyop
        ///endocardium : wsierdzie
        ///atrium, atria, auricles : przedsionki
        ///pericarditis : zapalenie osierdzia
        ///ventricles : komory
        ///atrioventricular : przedsionkowo komorowy
        ///mitral valve, bicuspid valve : zastawka mitralna, zastawka  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit10 {
            get {
                return ResourceManager.GetString("unit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string unit11 {
            get {
                return ResourceManager.GetString("unit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amino acid : aminokwas
        ///antacid : związek zobojętniający kwas
        ///bile : żółć
        ///carcinoma : rak
        ///chew : żuć
        ///chyme : miazga pokarmowa
        ///colitis : zapalenie okrężnicy
        ///diarrhoea : biegunka
        ///discomfort : dolegliwość, złe samopoczucie
        ///diverticulitis : zapalenie uchyłka
        ///erosion : nadżerka
        ///exacerbation : zaostrzenie
        ///excessive : nadmierny
        ///faeces : kał, stolec
        ///fat : tłuszcz
        ///fatty acid : kwas tłuszczowy
        ///gastritis : zapalenie, nieżyt żołądka
        ///glycerol : gliceryna, glicerol
        ///haematemesis : wymioty krwawe
        ///maltose  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit12 {
            get {
                return ResourceManager.GetString("unit12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anuria : bezmocz
        ///bladder : pęcherz
        ///calyx : kielich (nerki)
        ///cortex : kora
        ///dysuria : bolesne, trudne oddawanie moczu
        ///failure : niewydolność
        ///glomerulus : kłębuszek nerkowy
        ///haematuria : krwiomocz
        ///incontinence : nietrzymanie moczu
        ///kidney : nerka
        ///lesion : zmiana chorobowa
        ///medulla : rdzeń, substancja rdzenna
        ///neoplasm : nowotwór
        ///nephritis : zapalenie nerek
        ///nephroblastoma : nerczak niedojrzały, guz Wilmsa
        ///nephron : nefron
        ///nocturia : nadmierna diurcza nocna
        ///oliguria : skąpomocz
        ///pelvis : miedniczka n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit13 {
            get {
                return ResourceManager.GetString("unit13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abscess : ropień
        ///accelerate : przyśpieszać
        ///autonomic : autonomiczny
        ///axon : akson
        ///brain : Mózg
        ///bundle : pęczek, wiązka
        ///central : centralny
        ///cerebellum : móżdżek
        ///cerebrum : mózg
        ///concussion : wstrząs
        ///consciousness : przytomność
        ///degeneration : degeneracja, zwyrodnienie
        ///dementia : demencja
        ///dendrite : dendryt
        ///dizziness : zawrót głowy
        ///drowsiness : senność, ospałość
        ///encephalitis : zapalenie mózgu
        ///environment : otoczenie, środowisko
        ///epileptic seizure : napad padaczkowy
        ///fold : fałd, zagięcie
        ///gray m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit14 {
            get {
                return ResourceManager.GetString("unit14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aqueous humor : ciecz wodnista oka
        ///cataract : zaćma
        ///choroid : naczyniówka oka
        ///con : czopek
        ///concave : wklęsły
        ///conjunctiva : spojówka
        ///convex : wypukły
        ///cornea : rogówka
        ///cross-eye : zez zbieżny
        ///detachment : odwarstwianie się, odklejanie się
        ///eye : oko
        ///eyeball : gałka oczna
        ///eyebrow : brew
        ///eyelid : powieka
        ///eye socket : oczodół
        ///focus : skupiać, ogniskować
        ///glaucoma : jaskra
        ///hypermetropia : Dalekowzroczność
        ///imbalance : brak rónowagi
        ///iris : tęczówka
        ///lacrimal gland : gruczoł łzowy
        ///lens : soczewka
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit15 {
            get {
                return ResourceManager.GetString("unit15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acoustic nerve : nerw słuchowy
        ///anvil (Incus) : kowadełko
        ///athetosis : atetoza, powolne ruchy palców
        ///auditory : słuchowy
        ///pinna (auricle) : małżowina uszna
        ///cartilage : chrząstka, tkanka chrzęstna
        ///cerebral palsy : paraliż, porażenie mózgowe
        ///cochlea : ślimak
        ///convert : zamienić
        ///deafness : głuchota
        ///drum : bębenek
        ///ear : ucho
        ///earache : ból ucha
        ///enclose : otoczyć
        ///eustachian tube : trąbka eustahiusza, trąbka słuchowa
        ///external : zewnętrzny
        ///hammer (malleus) : młoteczek
        ///helix : spirala, helisa
        ///hearing : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit16 {
            get {
                return ResourceManager.GetString("unit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aim : cel celować
        ///approach : podejście
        ///area : obszar
        ///complain : skarżyć się, narzekać
        ///complaint : skarga, dolegliwość
        ///concern : zainteresować, dotyczyć, zajmować się
        ///consideration : rozwaga 
        ///take into consideration : wziąć, brać coś pod uwagę
        ///cure : leczyć, wyleczyć
        ///dietician : dietetyk
        ///duty : obowiązek, dyżur
        ///enviroment : otoczenie, środowisko
        ///examination : badanie
        ///physical examination : badanie fizykalne
        ///general practitioner : lekarz ogólny
        ///A gynaecologist : ginekolog
        ///indicate : wskazać, z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit17_1 {
            get {
                return ResourceManager.GetString("unit17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allergology : alergologia
        ///An immunologist : immunolog
        ///immunology : immunologia
        ///An anesthesiologist : anestezjolog
        ///anesthesiology : anestezjologia
        ///A geriatrician : geriatra
        ///geriatrics : geriatria
        ///A ophthalmologist : okulista
        ///ophthalmology : okulistyka
        ///psychiatrist : psychiatra
        ///psychiatry : psychiatria
        ///otolaryngology : otolaryngologia
        ///A general surgeon : chirurg
        ///surgery : chirurgia
        ///A neurologist : neurolog
        ///neurology : neurologia
        ///A plastic surgeon : chirurg plastyczny
        ///plastic surgery : Chirurg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit17_2 {
            get {
                return ResourceManager.GetString("unit17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿accessory : dodatkowy, pomocniczy
        ///aid : pomoc
        ///angiography : angiografia
        ///Auscultation : słuchiwanie
        ///Biopsy : biopsja
        ///Bronchoscopy : wziernikowanie oskrzeli
        ///Bruit : szmer serca
        ///Carry out : wykonywać
        ///Click : click, trzask (sercowy)
        ///coarse rales : rzężenie grubobańkowe
        ///Colorectoscopy : wziernikowanie okrężnicy i odbytu
        ///Complete blood count : morfologia krwi
        ///Confirm : potwierdzić
        ///crackle : trzeszczenie
        ///Crepitation : Trzeszczenie
        ///Detect : dostrzegać wykrywać
        ///Determine : określać, ustalać
        ///Duratio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit18 {
            get {
                return ResourceManager.GetString("unit18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What brings you here? : Co cie tu sprowadza?
        ///What are your complaints? : Jakie są twoje dolegliwości?
        ///What seems to be the problem? : Co wydaje się być problemem?
        ///How long have you had this pain? : Jak długo miałeś ten ból?
        ///How long does this pain last? : Jak długo ten ból trwał?
        ///When did the pain start? : Kiedy zaczął się ból?
        ///When did you first notice it? : Kiedy po raz pierwszy zauważyłeś go?
        ///where does it hurt? : Gdzie boli?
        ///Show me where the pain is? : Pokaż mi, gdzie jest ból?
        ///Which part of y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit18_questions {
            get {
                return ResourceManager.GetString("unit18_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bone marrow : szpik kostny
        ///counselling : poradnictwo
        ///donor : dawca
        ///excision : wycięcie
        ///immune system : układ odpornościowy
        ///immunosuppressant : środek immunosupresyjny
        ///laser : laser
        ///lithotripsy : kruszenie kamieni
        ///palliative : paliatywny, łagodzący
        ///recipient : biorca
        ///rejection : odrzucenie
        ///substitute : substytut, zastępowainie, podstawianie
        ///tiny : mały
        ///ultrasonography : ultrasonografia
        ///radiation therapy : radioterapia
        ///endoscope : endoskop
        ///transplant surgery : operacja przeszczepu
        ///hip joint : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit19_1 {
            get {
                return ResourceManager.GetString("unit19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporary : tymczasowy
        ///permanent : stały
        ///kidney stones : kamienie nerkowe
        ///retina detachment : odwarstwienie siatkówki
        ///hip joint degeneration : Zwyrodnienie stawu biodrowego
        ///impaired movement : zaburzenia ruchu
        ///healed leg fracture : Uzdrowienie nogi złamania
        ///respiratory distress : niewydolności oddechowej
        ///cardiac failure : Niewydolność serca
        ///rectal polyps : polipy odbytnicy
        ///Hypertension : nadciśnienie
        ///Hypoglycemia : hipoglikemia
        ///Macrocephaly : wielkogłowie
        ///Multigravida : wieloródka
        ///Oliguria : s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit19_2 {
            get {
                return ResourceManager.GetString("unit19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbness of the fingers : drętwienie palców
        ///dandruff : łupież
        ///arterial murmur : szmer tętniczej?
        ///retrosternal pain : ból zamostkowy
        ///cholecystolithiasis : Kamica pęcherzykowa
        ///dementia : demencja
        ///incontinence : nietrzymanie moczu
        ///coarse rales : rzężenia grubobańkowe
        ///tinnitus : szum w uszach
        ///acne : trądzik
        ///anuria : bezmocz
        ///epileptic seizures : napady padaczkowe
        ///crepitations : trzeszczenia
        ///migraine : migrena
        ///urticaria : pokrzywka
        ///heartburn : zgaga
        ///pleural friction : tarcia opłucnej
        ///tachycardia  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit19_3 {
            get {
                return ResourceManager.GetString("unit19_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anterior : przedni
        ///ascend : wstępować
        ///caudal : doogonowy
        ///comprise : zawierać, obejmować składać się
        ///contain : zawierać, mieścić w sobie
        ///couch : leżanka
        ///cranial : czaszkowy, głowowy
        ///descend : zstępować
        ///direct : skierować, bezpośredni
        ///distal : dystalny, dalszy
        ///dorsal : grzbietowy
        ///downwards : na/w dół, ku dołowi
        ///extend : rozciągać się, rozprzestrzeniać się
        ///forwards : naprzód, ku przodowi
        ///inferior : dolny, niższy
        ///lateral : boczny
        ///medial : środkowy
        ///parallel : równoległy
        ///pass : przejście, przech [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit2 {
            get {
                return ResourceManager.GetString("unit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adhesive plaster : przylepiec
        ///adhesive tape : Przylepiec
        ///anesthetic : środek znieczulający
        ///analgesic : środek przeciwbólowy
        ///antiallergic : środek przeciwalergiczny
        ///antibiotic : antybiotyk
        ///antipyretic : środek przeciwgorączkowy
        ///appointment : umówiony termin, zamówiona wizyta u lekarza
        ///auriscope : wziernik uszny
        ///cabinet : szafka
        ///calgul? : kalgul?
        ///cleanse : oczyścić
        ///constipation : zaparcie
        ///consulting room  : gabinet przyjęć lekarski
        ///couch : kozentka, leżanka
        ///disinfect : zdezynfekować
        ///disposable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit20 {
            get {
                return ResourceManager.GetString("unit20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auscultate : opukać
        ///pneumonia : zapalenie płuc
        ///anxious : niespokojny
        ///cyanotic : siniczy
        ///febrile : gorączkowy
        ///dyspnoeic : dusznością
        ///nauseated : mdłości
        ///tenderness : czułość
        ///rigidity : sztywność
        ///distension : nabrzmnienie
        ///hepatosplenomegaly : powiększenie wątroby i śledziony
        ///resonant : rezonansowy
        ///dull : głuchy
        ///crepitations : trzeszczenia
        ///creps : Trzeszczenia
        ///crackles : trzaski
        ///coarse rales : grube rzężenia
        ///fine rales : drobne rzężenia
        ///moist rales : wilgotne rzężenia
        ///wheezes : charczenie
        ///r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit20cz2 {
            get {
                return ResourceManager.GetString("unit20cz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anaesthetic room : sala do wprowadzania znieczulania ogólnego
        ///communicable disease : choroba zakaźna
        ///dispensary : apteka szpitalna
        ///emergency : nagły przypadek
        ///endowment : fundacja
        ///general hospital : szpital ogólny
        ///injure : zranić
        ///in-patient : chory leżący w szpitalu
        ///insurance : ubezpieczenie
        ///issue : wydawać
        ///medical ward : oddział wewnętrzny
        ///operating theatre: sala operacyjna
        ///out-patien department : przychodnia przy szpitalu, ambulatorium
        ///provide : dostarczyć, zapewnić
        ///require : wymagać
        ///resear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unit21 {
            get {
                return ResourceManager.GetString("Unit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to armpit : dół pachwowy
        ///bulb : bańka
        ///blunt : tępy
        ///collapse : zapaść
        ///constrict : skurczyś, zacisnąć
        ///fever : gorączka
        ///flush : zaczerwienienie, zaczerwienić się
        ///hypothalamus : podwzgórze
        ///infectious : zakaźny
        ///pyrexia : Gorączka
        ///range : zakres, zasięg
        ///record : zapisać
        ///shiver : drżeć, mieć dreszcze
        ///site : miejsce
        ///sweating : pocenie się
        ///dilate : rozszerzać
        ///restlessness : niepokój
        ///convulsions : drgawki
        ///chills : dreszcze
        ///expectorate: wypluć
        ///dyspnoea : duszność
        ///bronchitis : zapalenie oskrzeli
        ///be a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit22 {
            get {
                return ResourceManager.GetString("unit22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anxiety : niepokój, obawa
        ///carotid : szyjny
        ///femoral : udowy
        ///force : siła
        ///heart beat : bicie serca
        ///index finger : palec wskazujący
        ///infant : niemowlę
        ///middle finger : palec środkowy
        ///newborn : nowo narodzony, noworodek
        ///popliteal : podkolanowy
        ///pulse : puls
        ///radial : promieniowy
        ///reflection : odbicie, odzwierciedlenie
        ///relaxation : odprężenie
        ///temporal : skroniowy
        ///pumped : pompowana
        ///wrist : nadgarstek
        ///temples : świątynie
        ///groin : pachwina
        ///knee :kolano
        ///apical :koniuszka 
        ///apex : wierzchołek
        ///nipple : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit23 {
            get {
                return ResourceManager.GetString("unit23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply : zastosować
        ///blood pressure : ciśnienie krwi
        ///brachial artery : tętnica ramienna
        ///chart : karta gorączkowa pacjenta
        ///constant : stały
        ///cuff : mankiet
        ///deflate : wypuścić powietrze
        ///diastolic pressure : ciśnienie rozkurczowe
        ///inflate : napompować
        ///maintain : utrzymywać, podtrzymywać
        ///mercury : rtęć
        ///quantity : ilość
        ///slender : szczupły, smukły
        ///sphygmomanometer : sfygmomanometr
        ///systolic pressure : ciśnienie skurczowe
        ///vena cava : żyła główna
        ///ventricles : komory
        ///contract : kurczyć
        ///haemorrhage : krw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unit24 {
            get {
                return ResourceManager.GetString("Unit24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aspect : aspekt, strona oglądania
        ///buttock : pośladek
        ///cerebro-spinal : mózgowo rdzeniowy
        ///diabetic coma : śpiączka cukrzycowa
        ///disposable syringe : strzykawka jednorazowa
        ///fluid : płyn
        ///hydrocortisone acetate : octan hydrokorizonu
        ///infusion : wlew, infuzja
        ///injection : zastrzyk
        ///intra-articular : dostawowy(zastrzyk)
        ///intradermal : śródskórny
        ///intramuscular : domięśniowy
        ///intrathecal : dooponowy
        ///intravenous : dożylny
        ///irritant : drażniący
        ///leukaemia : białaczka
        ///lumbar puncture : punkcja lędźwiowa
        ///meningi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit25 {
            get {
                return ResourceManager.GetString("unit25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blood vessel : naczynie krwionośne
        ///connective tissue : tkanka łączna
        ///dermis : skóra właściwa
        ///epidermis : naskórek
        ///epithelium : nabłonek
        ///flat : płaski
        ///hair : włosy
        ///keratinization : rogowacenie, keratynizacja
        ///layer : Warstwa
        ///mammary gland : gruczoł mleczny
        ///melanin : melanina
        ///nail : paznokieć
        ///sebaceous gland : gruczoł łojowy
        ///skin : skóra
        ///sole : podeszwa
        ///subcutaneous : podskórny
        ///sweat gland : gruczoł potowy
        ///tough : mocny wytrzymały
        ///duct : kanał
        ///cornified : zrogowaciały
        ///stratum : warstwa
        ///ger [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit3 {
            get {
                return ResourceManager.GetString("unit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acne : trądzik
        ///carbon dioxide : dwutlenek węgla
        ///crust : strup
        ///damage : szkoda, uszkodzenie, uszkodzić
        ///dermatitis : zapalenie skóry
        ///dermatomycosis : grzybica
        ///dissolved : rozpuszczony
        ///ear wax : woskowina uszna
        ///eczema : egzema
        ///erythema : rumień
        ///evaporate : parować, ulatniać się
        ///excessive : nadmierny
        ///excoriation : otarcie skóry, zadrapanie
        ///excretory organ : organ wydalniczy
        ///expose : wystawić, narazić
        ///fissure : szczelina, pęknięcie
        ///furuncle : czyrak nogi
        ///injury : zranienie, uszkodzenie
        ///irritati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit4 {
            get {
                return ResourceManager.GetString("unit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdominopelvic cavity : jama brzuszno-miednicza
        ///bound : ograniczać, wiązać
        ///brain : mózg
        ///cranial cavity : jama czaszkowa
        ///feverish : gorączkowy
        ///heart : serce
        ///large intestine : jelito grube
        ///liver : wątroba
        ///lung : płuco
        ///pancreas : trzustka
        ///pelvis : miednica
        ///peritoneum : otrzewna
        ///rectum : odbyt
        ///reproductive organs : organy rozrodcze
        ///rib : żebro
        ///slightly : nieznacznie
        ///small intestine : jelito cienkie
        ///sort out : rozwiązać
        ///spinal column : kręgosłup
        ///spleen : śledziona
        ///sternum : mostek
        ///stomach :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit5 {
            get {
                return ResourceManager.GetString("unit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appendicular : odnoszący się do kończyn
        ///axial : osiowy
        ///carpal : nadgarstkowy
        ///cervical : szyjny
        ///clavicle : obojczyk
        ///coccyx : kość guziczna, kość ogonowa
        ///cranium : mózgoczaszka
        ///femur : kość udowa
        ///fibula : kość strzałkowa
        ///girdle : obręcz
        ///humerus : kość ramieniowa
        ///lumbar : lędźwiowy
        ///metacarpal : śródręczny
        ///metatarsal : śródstopowy
        ///patella : rzepka kolanowa
        ///phalanges(pl.) phalanx(sing.) : paliczki
        ///radius : kość promieniowa
        ///sacrum : kość krzyżowa
        ///scapula : łopatka
        ///skull : czaszka
        ///tibia : kość  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit6 {
            get {
                return ResourceManager.GetString("unit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alveolus : pęcherzyk płucny
        ///respiratory system : układ oddechowy
        ///sac  : pęcherzyk
        ///tonsil : migdałek
        ///visceral : trzewny
        ///attach : przyłączyć
        ///basc : podstawa
        ///bloodstream : krwioobieg
        ///pharynx : gardło
        ///larynx : Krtań
        ///trachea : tchawica
        ///bronchi (pl), bronchus (sing)  : oskrzela
        ///bronchiole : oskrzelik
        ///cone : stożek
        ///factor : czynnik
        ///hoarseness : chrypka
        ///hurt : zranienie
        ///laryngopharynx : krtaniowa część gardła
        ///line : linia, wyścielić
        ///lobe : płat
        ///lung : płuco
        ///alveoli of the lungs : pęcherzyki plu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit7 {
            get {
                return ResourceManager.GetString("unit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to respiration : oddychanie
        ///reversible : odwracalny
        ///absorb : wchłaniać
        ///absorption : wchłanianie
        ///sacs : woreczki
        ///diffuses : przenikać, rozproszony, rozpraszać
        ///accessory : dodatkowy, pomocniczy
        ///accessory organs : poboczne organy
        ///intercostal muscles : mięśni międzyżebrowych
        ///intercostal : międzyżebrowe
        ///involve : wciągnąć (w proces chorobowy)
        ///ribs : żebra
        ///blaish : niebieskawy
        ///capillary : naczynie włosowate
        ///consecutive : kolejny
        ///distension : rozszerzanie
        ///enlarge : powiększyć
        ///exhale : wydychać
        ///distr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit8 {
            get {
                return ResourceManager.GetString("unit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anemia : anemia
        ///fluid : płyn
        ///carbon dioxide : dwutlenek węgla
        ///plasma : osocze krwi
        ///carbohydrates : węglowodany
        ///dissolved : rozpuszczony
        ///dissolve : rozpuścić
        ///dizziness : zawrót głowy
        ///suspended : zawieszony
        ///lung capillary : kapilary płuc
        ///granulocytes : granulocyty
        ///basophils : bazofile, leukocyt zasadochłonny
        ///eosinophils : granulocyt eozynochłonny
        ///neutrophils : neutrofil, granulocyt obojętnochłonny
        ///monocytes : monocyty
        ///ingest : przyjmować pokarm,
        ///blood coagulation, blood clotting : krzepnięcia  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit9 {
            get {
                return ResourceManager.GetString("unit9", resourceCulture);
            }
        }
    }
}
